Update shflags 1.0.3 to 1.2.3
Also update the path from which it's installed, as it has changed
between releases.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

diff --git a/scripts/shared/lib/shflags b/scripts/shared/lib/shflags
--- a/scripts/shared/lib/shflags
+++ b/scripts/shared/lib/shflags
@@ -10,7 +10,7 @@ ensure_shflags() {
 
     if [ ! -s .shflags ]; then
         echo "Downloading shflags ${SHFLAGS_VERSION}"
-        if ! curl -L "https://raw.githubusercontent.com/kward/shflags/${SHFLAGS_VERSION}/src/shflags" > .shflags; then
+        if ! curl -L "https://raw.githubusercontent.com/kward/shflags/v${SHFLAGS_VERSION}/shflags" > .shflags; then
             rm -f .shflags
             echo "$0 needs shflags in /usr/share/shflags/shflags or locally as .shflags." 1>&2
             echo "It was unable to download it; please install it and try again." 1>&2
@@ -18,8 +18,10 @@ ensure_shflags() {
         fi
     fi
 
+    # Avoid failures because FLAGS_ARGC becomes read-only
+    unset FLAGS_ARGC
     . ./.shflags
 }
 
-SHFLAGS_VERSION=${SHFLAGS_VERSION:=1.0.3}
+SHFLAGS_VERSION=${SHFLAGS_VERSION:=1.2.3}
 ensure_shflags
